const state = { cart: [], products: [], pickerProducts: [], selectedProduct: null, expandedHistory: null, history: null, scannerStream: null, scannerFrame: null, scannerTarget: null };
const $ = (selector) => document.querySelector(selector);
let requestId = 0;
const worker = new Worker('./sqlite-worker.js', { type: 'module' });
const pending = new Map();
worker.onmessage = ({ data }) => { const job = pending.get(data.id); if (!job) return; pending.delete(data.id); data.error ? job.reject(new Error(data.error)) : job.resolve(data.result); };
function api(type, payload) { return new Promise((resolve, reject) => { const id = ++requestId; pending.set(id, { resolve, reject }); worker.postMessage({ id, type, payload }); }); }
function rupiah(value) { return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(Number(value || 0)); }
function qty(value) { return Number(value || 0).toLocaleString('id-ID', { maximumFractionDigits: 2 }); }
function escapeHtml(value) { return String(value ?? '').replace(/[&<>'"]/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' })[char]); }
function today(offset = 0) { const date = new Date(); date.setDate(date.getDate() + offset); return date.toISOString().slice(0, 10); }
function toast(message, bad = false) { const box = $('#toast'); box.textContent = message; box.className = `show ${bad ? 'bad' : ''}`; setTimeout(() => { if (box.textContent === message) box.className = ''; }, 3600); }
function metric(icon, label, value) { return `<article class="metric-card"><span class="metric-icon">${icon}</span><small>${label}</small><strong>${value}</strong></article>`; }
function empty(message) { return `<div class="empty-state"><div>🛒</div><p>${message}</p></div>`; }
function askConfirm({ title = 'Konfirmasi', message, approve = 'Lanjutkan', danger = false }) { return new Promise((resolve) => { $('#confirm-title').textContent = title; $('#confirm-message').textContent = message; $('#confirm-approve').textContent = approve; $('#confirm-approve').className = danger ? 'danger' : 'primary'; $('#confirm-dialog').showModal(); const finish = (answer) => { $('#confirm-dialog').close(); resolve(answer); }; $('#confirm-cancel').onclick = () => finish(false); $('#confirm-approve').onclick = () => finish(true); }); }

async function loadDashboard(search = $('#product-filter').value) {
  const [summary, products] = await Promise.all([api('dashboard'), api('products', { search })]);
  state.products = products;
  $('#dashboard-metrics').innerHTML = [metric('▣', 'Jenis Barang', summary.jenis), metric('▤', 'Total Stok', qty(summary.stok)), metric('▰', 'Nilai Stok', rupiah(summary.nilai)), metric('⚠', 'Stok Menipis', summary.menipis)].join('');
  $('#stock-alert').innerHTML = Number(summary.menipis) ? `<div class="alert">⚠ &nbsp;Ada barang dengan stok di bawah 5.</div>` : '';
  renderProductList();
}
function renderProductList() {
  const target = $('#products-list');
  target.innerHTML = state.products.length ? state.products.map((product) => { const low = Number(product.stok) < 5; return `<article class="product-card" data-edit="${product.id}"><span class="product-icon">${low ? '⚠' : '▣'}</span><div><strong>${escapeHtml(product.nama)}</strong><small>${escapeHtml(product.barcode || 'Tanpa barcode')}<br>${escapeHtml(product.satuan)} · ${rupiah(product.harga)}</small></div><div class="stock ${low ? 'low' : ''}"><strong>${qty(product.stok)}</strong><small>stok</small></div></article>`; }).join('') : empty('Belum ada barang. Tekan Tambah Barang.');
  target.querySelectorAll('[data-edit]').forEach((node) => node.onclick = () => openProduct(state.products.find((product) => product.id === Number(node.dataset.edit))));
}
async function loadPosSearch(search = $('#product-search').value) { state.products = search.trim() ? await api('products', { search }) : []; renderSearchResults(); }
function renderSearchResults() {
  const target = $('#product-results');
  if (!$('#product-search').value.trim()) { target.innerHTML = ''; return; }
  target.innerHTML = state.products.length ? state.products.map((product) => `<button class="search-result" data-pick="${product.id}" ${Number(product.stok) <= 0 ? 'disabled' : ''}><span class="product-icon">▣</span><span><strong>${escapeHtml(product.nama)}</strong><small>Stok ${qty(product.stok)} · ${escapeHtml(product.barcode || '')}</small></span><strong>${rupiah(product.harga)}</strong></button>`).join('') : '<div class="card muted">Barang tidak ditemukan.</div>';
  target.querySelectorAll('[data-pick]').forEach((button) => button.onclick = () => askQuantity(state.products.find((product) => product.id === Number(button.dataset.pick))));
}
async function openPicker() { state.pickerProducts = await api('products'); $('#picker-search').value = ''; renderPicker(); $('#picker-dialog').showModal(); $('#picker-search').focus(); }
function renderPicker() { const query = $('#picker-search').value.toLowerCase(); const rows = state.pickerProducts.filter((p) => p.nama.toLowerCase().includes(query) || String(p.barcode || '').toLowerCase().includes(query)); $('#picker-list').innerHTML = rows.length ? rows.map((product) => `<button class="picker-row" data-pick="${product.id}" ${Number(product.stok) <= 0 ? 'disabled' : ''}><span class="product-icon">▣</span><span><strong>${escapeHtml(product.nama)}</strong><small>${escapeHtml(product.barcode || '')} · Stok ${qty(product.stok)}</small></span><strong>${rupiah(product.harga)}</strong></button>`).join('') : '<p class="muted">Barang tidak ditemukan.</p>'; $('#picker-list').querySelectorAll('[data-pick]').forEach((button) => button.onclick = () => { $('#picker-dialog').close(); askQuantity(state.pickerProducts.find((product) => product.id === Number(button.dataset.pick))); }); }
function askQuantity(product) { state.selectedProduct = product; $('#quantity-title').textContent = product.nama; $('#quantity-value').value = '1'; $('#quantity-dialog').showModal(); $('#quantity-value').focus(); }
function addToCart(product, amount) { const number = Number(amount); if (!Number.isFinite(number) || number <= 0) return toast('Jumlah harus lebih dari 0.', true); const found = state.cart.find((item) => item.id === product.id); const current = found ? found.qty : 0; if (current + number > Number(product.stok)) return toast(`Stok ${product.nama} tidak cukup.`, true); if (found) found.qty += number; else state.cart.push({ ...product, qty: number }); renderCart(); toast(`✓ ${product.nama} masuk keranjang`); }
function renderCart() {
  const target = $('#cart-items'); const checkout = $('#checkout-card');
  if (!state.cart.length) { target.innerHTML = empty('Keranjang masih kosong'); checkout.hidden = true; return; }
  target.innerHTML = state.cart.map((item) => `<article class="cart-item card"><span class="product-icon">▣</span><div><strong>${escapeHtml(item.nama)}</strong><small>${rupiah(item.harga)}<br>Subtotal: <b>${rupiah(item.harga * item.qty)}</b></small></div><label class="qty-input">Qty<input data-qty="${item.id}" type="number" min="0.01" step="0.01" value="${item.qty}" /></label><button class="delete-icon" data-remove="${item.id}" aria-label="Hapus ${escapeHtml(item.nama)}">⌫</button></article>`).join('');
  target.querySelectorAll('[data-qty]').forEach((input) => input.onchange = () => { const item = state.cart.find((row) => row.id === Number(input.dataset.qty)); const number = Number(input.value); if (number > 0 && number <= item.stok) { item.qty = number; renderCart(); } else { toast(`Qty maksimal ${qty(item.stok)}.`, true); renderCart(); } });
  target.querySelectorAll('[data-remove]').forEach((button) => button.onclick = () => { state.cart = state.cart.filter((item) => item.id !== Number(button.dataset.remove)); renderCart(); });
  checkout.hidden = false; $('#cart-total').textContent = rupiah(cartTotal()); updatePaymentUi();
}
function cartTotal() { return state.cart.reduce((sum, item) => sum + Math.round(item.harga * item.qty), 0); }
function updatePaymentUi() { const total = cartTotal(); const cash = $('#payment-method').value === 'Cash'; $('#paid-field').hidden = !cash; if (!cash) $('#amount-paid').value = total; const paid = Number($('#amount-paid').value || 0); $('#change-preview').textContent = cash ? (paid >= total ? `Kembalian: ${rupiah(paid - total)}` : `Kurang: ${rupiah(total - paid)}`) : 'Pembayaran non-tunai sesuai total.'; }

async function loadHistory() { const result = await api('history', { from: $('#history-from').value, to: $('#history-to').value }); state.history = result; $('#history-metrics').innerHTML = [metric('▰', 'Pendapatan', rupiah(result.summary.pendapatan)), metric('☷', 'Transaksi', result.summary.transaksi)].join(''); renderHistory(); }
function renderHistory() { const target = $('#history-list'); const transactions = state.history?.transactions || []; target.innerHTML = transactions.length ? transactions.map((row) => { const open = state.expandedHistory === row.id; return `<article class="history-card card"><button class="history-head" data-expand="${row.id}"><span><strong>Transaksi #${row.id}</strong><small>${escapeHtml(row.waktu.replace(' ', ' · '))} · ${escapeHtml(row.metode_bayar)}</small></span><strong>${rupiah(row.total_bayar)} ${open ? '⌃' : '⌄'}</strong></button>${open ? `<div class="history-details">${row.details.map((detail) => `<div><span>${escapeHtml(detail.nama_barang)}<small>${qty(detail.qty)} × ${rupiah(detail.harga_satuan)}</small></span><strong>${rupiah(detail.subtotal)}</strong></div>`).join('')}<hr><div><span>Dibayar</span><strong>${rupiah(row.dibayar)}</strong></div>${Number(row.kembalian) > 0 ? `<div><span>Kembalian</span><strong>${rupiah(row.kembalian)}</strong></div>` : ''}<button class="delete-transaction" data-delete-transaction="${row.id}">⌫ Hapus transaksi & kembalikan stok</button></div>` : ''}</article>`; }).join('') : empty('Tidak ada transaksi pada periode ini.');
  target.querySelectorAll('[data-expand]').forEach((button) => button.onclick = () => { state.expandedHistory = state.expandedHistory === button.dataset.expand ? null : button.dataset.expand; renderHistory(); });
  target.querySelectorAll('[data-delete-transaction]').forEach((button) => button.onclick = async () => { if (!await askConfirm({ title: 'Hapus transaksi?', message: 'Transaksi ini akan dihapus dan stok semua barang akan dikembalikan.', approve: 'Hapus transaksi', danger: true })) return; await api('deleteTransaction', { id: button.dataset.deleteTransaction }); state.expandedHistory = null; await loadHistory(); await loadDashboard(); toast('Transaksi dihapus, stok dikembalikan.'); });
}
function downloadHistory() { const rows = state.history?.transactions || []; if (!rows.length) return toast('Tidak ada data untuk diunduh.', true); const header = ['ID Transaksi','Waktu','Metode Pembayaran','Nama Barang','Harga Satuan','Qty','Subtotal','Dibayar','Kembalian']; const escapeCsv = (value) => `"${String(value ?? '').replaceAll('"', '""')}"`; const lines = [header, ...rows.flatMap((row) => row.details.map((detail) => [row.id,row.waktu,row.metode_bayar,detail.nama_barang,detail.harga_satuan,detail.qty,detail.subtotal,row.dibayar,row.kembalian]))].map((line) => line.map(escapeCsv).join(',')); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob(['\uFEFF' + lines.join('\n')], { type: 'text/csv;charset=utf-8' })); link.download = `laporan-penjualan-${$('#history-from').value}-sd-${$('#history-to').value}.csv`; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); }

async function loadReport() { const data = await api('report', { from: $('#report-from').value, to: $('#report-to').value }); const m = data.metrics; $('#report-metrics').innerHTML = [metric('▰','Pendapatan',rupiah(m.total)),metric('☷','Transaksi',m.transaksi),metric('▣','Item Terjual',qty(m.item)),metric('⌁','Rata-rata',rupiah(m.rata_rata))].join(''); renderTrend(data.trend); $('#top-qty').innerHTML = productBars(data.topQty, 'qty', (value) => `${qty(value)} terjual`); $('#top-revenue').innerHTML = productBars(data.topRevenue, 'pendapatan', rupiah); $('#payment-report').innerHTML = data.payments.length ? data.payments.map((item) => { const percent = Number(m.total) ? Number(item.total) / Number(m.total) * 100 : 0; return `<article class="payment-card card"><div><strong>${escapeHtml(item.metode_bayar)}</strong><strong>${rupiah(item.total)}</strong></div><div class="progress"><i style="width:${percent}%"></i></div><small>${percent.toFixed(1)}% · ${item.jumlah} transaksi</small></article>`; }).join('') : empty('Belum ada data.'); }
function renderTrend(data) { const target = $('#trend-chart'); if (!data.length) { target.innerHTML = '<p class="muted">Belum ada data.</p>'; return; } const max = Math.max(...data.map((item) => Number(item.total))); target.innerHTML = `<div class="bars">${data.map((item) => `<div><i style="height:${Math.max(3, Number(item.total) / max * 100)}%" title="${rupiah(item.total)}"></i><small>${escapeHtml(item.tanggal.slice(5))}</small></div>`).join('')}</div>`; }
function productBars(items, key, format) { if (!items.length) return '<p class="muted">Belum ada data.</p>'; const max = Math.max(...items.map((item) => Number(item[key]))); return `<ol class="product-bars">${items.map((item) => `<li><div><span>${escapeHtml(item.nama_barang)}</span><strong>${format(item[key])}</strong></div><div class="progress"><i style="width:${Number(item[key]) / max * 100}%"></i></div></li>`).join('')}</ol>`; }

function openProduct(product = {}) { $('#product-dialog-title').textContent = product.id ? 'Ubah Barang' : 'Tambah Barang'; $('#product-id').value = product.id || ''; $('#product-barcode').value = product.barcode || ''; $('#product-name').value = product.nama || ''; $('#product-unit').value = product.satuan || 'Pcs'; $('#product-price').value = product.harga ?? ''; $('#product-stock').value = product.stok ?? ''; $('#product-dialog').showModal(); }
function showView(view) { document.querySelectorAll('.view').forEach((node) => node.classList.toggle('active', node.id === `view-${view}`)); document.querySelectorAll('.nav-button').forEach((node) => node.classList.toggle('active', node.dataset.view === view)); const meta = { dashboard:'📦 Dashboard Barang',pos:'💵 Kasir',history:'📊 Histori Penjualan',reports:'📈 Rekap Penjualan' }; $('#app-title').textContent = meta[view]; document.body.dataset.view = view; if (view === 'dashboard') loadDashboard(); if (view === 'history') loadHistory(); if (view === 'reports') loadReport(); }
function stopScanner() { if (state.scannerFrame) cancelAnimationFrame(state.scannerFrame); state.scannerFrame = null; if (state.scannerStream) state.scannerStream.getTracks().forEach((track) => track.stop()); state.scannerStream = null; $('#scanner-video').srcObject = null; if ($('#scanner-dialog').open) $('#scanner-dialog').close(); }
async function useBarcode(code) { const value = code.trim(); if (!value) return; const target = state.scannerTarget; stopScanner(); if (target === 'product') { $('#product-barcode').value = value; toast('Barcode berhasil diisi.'); return; } const products = await api('products', { search: value }); const product = products.find((item) => String(item.barcode) === value); if (product) { askQuantity(product); return; } if (await askConfirm({ title: 'Barcode tidak ditemukan', message: `Barcode ${value} belum ada di database. Tambahkan barang baru?`, approve: 'Tambah Barang' })) openProduct({ barcode: value, satuan: 'Pcs', stok: 1 }); }
async function openScanner(target) { state.scannerTarget = target; $('#scanner-manual').value = ''; $('#scanner-status').textContent = 'Membuka kamera…'; $('#scanner-dialog').showModal(); if (!navigator.mediaDevices?.getUserMedia) { $('#scanner-status').textContent = 'Kamera tidak tersedia pada browser ini. Gunakan input barcode manual di bawah.'; return; } try { state.scannerStream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: 'environment' } }, audio: false }); const video = $('#scanner-video'); video.srcObject = state.scannerStream; await video.play(); if (!('BarcodeDetector' in window)) { $('#scanner-status').textContent = 'Pemindai otomatis belum didukung browser ini. Masukkan barcode manual di bawah.'; return; } const detector = new BarcodeDetector({ formats: ['ean_13', 'ean_8', 'code_128', 'code_39', 'upc_a', 'upc_e', 'qr_code'] }); $('#scanner-status').textContent = 'Arahkan kamera ke barcode.'; const scan = async () => { if (!state.scannerStream) return; try { const codes = await detector.detect(video); if (codes[0]?.rawValue) { await useBarcode(codes[0].rawValue); return; } } catch {} state.scannerFrame = requestAnimationFrame(scan); }; scan(); } catch (error) { $('#scanner-status').textContent = 'Kamera tidak dapat dibuka. Izinkan akses kamera atau masukkan barcode manual.'; } }

document.querySelectorAll('.nav-button').forEach((button) => button.onclick = () => showView(button.dataset.view));
$('#product-filter').oninput = () => loadDashboard(); $('#clear-product-filter').onclick = () => { $('#product-filter').value = ''; loadDashboard(); };
$('#product-search').oninput = () => loadPosSearch(); $('#pick-product').onclick = openPicker; $('#picker-search').oninput = renderPicker; $('#scan-button').onclick = () => openScanner('pos'); $('#pos-scan').onclick = () => openScanner('pos'); $('#product-scan').onclick = () => openScanner('product'); $('#scanner-close').onclick = stopScanner; $('#scanner-submit').onclick = () => useBarcode($('#scanner-manual').value); $('#scanner-manual').onkeydown = (event) => { if (event.key === 'Enter') { event.preventDefault(); useBarcode($('#scanner-manual').value); } };
$('#new-product').onclick = () => openProduct();
$('#product-form').onsubmit = async (event) => { event.preventDefault(); try { await api('saveProduct', { id: $('#product-id').value, barcode: $('#product-barcode').value, nama: $('#product-name').value, satuan: $('#product-unit').value, harga: $('#product-price').value, stok: $('#product-stock').value }); $('#product-dialog').close(); await loadDashboard(); toast('Barang berhasil disimpan.'); } catch (error) { toast(error.message, true); } };
document.querySelectorAll('[data-close]').forEach((button) => button.onclick = () => { const dialog = $(`#${button.dataset.close}`); if (dialog.open) dialog.close(); });
$('#quantity-form').onsubmit = (event) => { event.preventDefault(); $('#quantity-dialog').close(); addToCart(state.selectedProduct, $('#quantity-value').value); };
$('#amount-paid').oninput = updatePaymentUi; $('#payment-method').onchange = updatePaymentUi; $('#clear-cart').onclick = () => { state.cart = []; renderCart(); };
$('#checkout').onclick = async () => { try { const result = await api('checkout', { cart: state.cart, metode: $('#payment-method').value, dibayar: $('#amount-paid').value }); state.cart = []; $('#amount-paid').value = ''; $('#payment-method').value = 'Cash'; renderCart(); await loadDashboard(); toast(`✓ Transaksi berhasil disimpan. Kembalian ${rupiah(result.kembalian)}`); } catch (error) { toast(error.message, true); } };
$('#history-from').onchange = loadHistory; $('#history-to').onchange = loadHistory; $('#download-history').onclick = downloadHistory; $('#report-from').onchange = loadReport; $('#report-to').onchange = loadReport;
$('#backup-open').onclick = () => $('#backup-dialog').showModal(); $('#export-db').onclick = async () => { const bytes = await api('export'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([bytes], { type: 'application/x-sqlite3' })); link.download = `kasir-lokal-${today()}.sqlite`; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); };
$('#import-db').onchange = async (event) => { const file = event.target.files[0]; if (!file) return; $('#import-name').textContent = file.name; if (!await askConfirm({ title: 'Pulihkan database?', message: 'Semua data lokal browser ini akan diganti dengan isi file yang dipilih.', approve: 'Pulihkan database', danger: true })) return; try { await api('import', { bytes: await file.arrayBuffer() }); state.cart = []; renderCart(); await loadDashboard(); $('#backup-dialog').close(); toast('Database berhasil dipulihkan.'); } catch (error) { toast(`Impor gagal: ${error.message}`, true); } };
$('#reset-db').onclick = async () => { if (!await askConfirm({ title: 'Hapus semua data?', message: 'Seluruh barang dan histori transaksi lokal akan hilang dari browser ini.', approve: 'Hapus semua data', danger: true })) return; await api('reset'); state.cart = []; renderCart(); await loadDashboard(); $('#backup-dialog').close(); toast('Database lokal dikosongkan.'); };

(async () => { try { await api('init'); $('#history-from').value = today(); $('#history-to').value = today(); $('#report-from').value = today(-30); $('#report-to').value = today(); await loadDashboard(); renderCart(); $('#loading-screen').remove(); $('#app').hidden = false; } catch (error) { $('#loading-screen').innerHTML = `<strong>Database lokal belum tersedia</strong><p>${escapeHtml(error.message)}</p><small>Jalankan melalui <code>node server.mjs</code>, bukan dengan membuka file HTML langsung.</small>`; } })();
